### ISSUE TITLE
Detect a chef_handler resource with the supports property

### ISSUE THREAD

**Issue by tas50** [chef/cookstyle#106]
### What category of cop is this?:

Please try to select as few as possible.

- [x] Deprecation - A cop that alerts to a deprecation in the Chef Infra Client
- [ ] Correctness - A cop that alerts when incorrect coding behavior is being used
- [ ] Sharing - A cop that alerts to missing functionality necessary for sharing cookboooks with others
- [ ] Style - A cop that alerts to a style best practice
- [ ] Simplification - A cop that alerts to ways code can be simplified through refactoring
- [ ] Effortless - A cop that alerts on code that must be resolved to move to the Effortless pattern
- [ ] Policyfiles - A cop that alerts on code that must be resolved to move to the Policyfiles pattern

### Describe the new cop:
We renamed the supports property to type to avoid confusion. We should autocorrect this anywhere we find it.

### What it would trigger on:
```ruby
chef_handler 'whatever' do
  supports 'foo'
end
````

### What it would autocorrect to if applicable
```ruby
chef_handler 'whatever' do
  type 'foo'
end
````

See: https://github.com/chef/chef/blob/master/lib/chef/resource/chef_handler.rb#L47

**Comment by afiune** [comment]
Closed by https://github.com/chef/cookstyle/pull/326
