### ISSUE TITLE
Attribute assignment does not specify precedence

### ISSUE THREAD

**Issue by tas50** [chef/cookstyle#148]
### What category of cop is this?:

Please try to select as few as possible.

- [ ] Deprecation - A cop that alerts to a deprecation in the Chef Infra Client
- [ ] Correctness - A cop that alerts when incorrect coding behavior is being used
- [ ] Sharing - A cop that alerts to missing functionality necessary for sharing cookboooks with others
- [ ] Style - A cop that alerts to a style best practice
- [ ] Simplification - A cop that alerts to ways code can be simplified through refactoring
- [ ] Effortless - A cop that alerts on code that must be resolved to move to the Effortless pattern
- [ ] Policyfiles - A cop that alerts on code that must be resolved to move to the Policyfiles pattern

### Describe the new cop:
It's required to set the attribute precedence level in an assignment

### What it would trigger on:

```ruby
node['foo'] = 'bar'
```

**Comment by tyler-ball** [comment]
Closing as a dup of chef/cookstyle#250
