### ISSUE TITLE
Possible Issue with cookstyle and http file inherited config files

### ISSUE THREAD

**Issue by brentm5** [chef/cookstyle#2]
I am not sure if this is an issue with cookstyle or rubocop core.  I have only seen it happen when using cookstyle however.  It seems to happens when it can't download a file randomly from an http endpoint.  In our case it shows much more when we run it in jenkins as it does a clean before build so that file always gets deleted.  I have not had this issue with rubocop so I am not sure if anything in cookstyle could cause this. 

```
Running shell script
+ cookstyle .
No such file or directory @ rb_sysopen - /jenkins/workspace/cookbook/.rubocop-https---raw-githubusercontent-com-rubocop-rules-chef-master-rubocop-yml
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.39.0/lib/rubocop/config_loader.rb:143:in `read'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.39.0/lib/rubocop/config_loader.rb:143:in `load_yaml_configuration'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.39.0/lib/rubocop/config_loader.rb:35:in `load_file'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.39.0/lib/rubocop/config_loader.rb:81:in `block in base_configs'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.39.0/lib/rubocop/config_loader.rb:68:in `map'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.39.0/lib/rubocop/config_loader.rb:68:in `base_configs'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.39.0/lib/rubocop/config_loader_resolver.rb:22:in `resolve_inheritance'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.39.0/lib/rubocop/config_loader.rb:38:in `load_file'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.39.0/lib/rubocop/config_loader.rb:97:in `configuration_from_file'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.39.0/lib/rubocop/config_store.rb:41:in `for'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.39.0/lib/rubocop/cli.rb:88:in `apply_default_formatter'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.39.0/lib/rubocop/cli.rb:26:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.39.0/bin/rubocop:14:in `block in <top (required)>'
/opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.39.0/bin/rubocop:13:in `<top (required)>'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/cookstyle-0.0.1/bin/cookstyle:13:in `load'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/cookstyle-0.0.1/bin/cookstyle:13:in `<top (required)>'
/opt/chefdk/bin/cookstyle:16:in `load'
/opt/chefdk/bin/cookstyle:16:in `<main>'
```

**Comment by lamont-granquist** [comment]
It could be a bug in the rubocop-0.39.0 that cookstyle is specifically pinned to?  cookstyle itself doesn't do anything that'd affect this, though, there's really no substantial 'code' in cookstyle its just a config wrapper around rubocop.

**Comment by bigbam505** [comment]
I was running rubocop (not sure of the version) and did not have any issue until we started using cookstyle exclusively.  Not sure if there could be a race condition in what cookstyle overrides since it does change what files get loaded by default.  Ill go ahead and see if I can recreate this on rubocop 0.39.0 proper.  If I can I will close this and create an issue on rubocop.

**Comment by lamont-granquist** [comment]
it may also be fixed in current rubocop.  however, i just tried to bump cookstyle+chefstyle to 0.41.1 and chefstyle failed miserably on chef/chef (chefstyle and chefstyle -a found different sets of busted cops which is a showstopper)

**Comment by lamont-granquist** [comment]
if this is a race condition its also a race condition in the underlying rubocop config loader -- we just abuse it, we don't really change anything.

**Comment by tas50** [comment]
@brentm5 We're about to bump to Rubocop 0.46 (monday probably) so this might just magically go away

**Comment by brentm5** [comment]
@tas50 thanks for the update. We actually encountered this when trying to essentially create a less awesome version of cookstyle. (just a shared rubocop.yml file) since this broke everywhere and cookstyle was more inclusive (actually locking down rubocop) we just standardized on using cookstyle and no external shared rubocop file.   You can decide if you want to keep this open or not but since no one else seems to have this issue and we have deprecated our usage its fine to close it from my point of view.

**Comment by lamont-granquist** [comment]
@tas50 you might actually go the other way and see this bug pop up:  https://github.com/chef/chefstyle/issues/39

IDK what the hell is causing that one.
