### ISSUE TITLE
Detect searching for roles or environments

### ISSUE THREAD

**Issue by tas50** [chef/cookstyle#204]
### What category of cop is this?:

Please try to select as few as possible.

- [ ] Deprecation - A cop that alerts to a deprecation in the Chef Infra Client
- [ ] Correctness - A cop that alerts when incorrect coding behavior is being used
- [ ] Sharing - A cop that alerts to missing functionality necessary for sharing cookboooks with others
- [ ] Style - A cop that alerts to a style best practice
- [ ] Simplification - A cop that alerts to ways code can be simplified through refactoring
- [ ] Effortless - A cop that alerts on code that must be resolved to move to the Effortless pattern
- [ ] Policyfiles - A cop that alerts on code that must be resolved to move to the Policyfiles pattern

### Describe the new cop:
This would be another off by default rule, but if we're converting users to Policyfiles we want to detect when they are using roles / environments. This would help with that.

### What it would trigger on:

```ruby
search(:node, "role:foo AND chef_environment:bar")
```

**Comment by afiune** [comment]
Closed by https://github.com/chef/cookstyle/pull/368
