### ISSUE TITLE
Detect common node method format attributes

### ISSUE THREAD

**Issue by tas50** [chef/cookstyle#206]
### What category of cop is this?:

Please try to select as few as possible.

- [ ] Deprecation - A cop that alerts to a deprecation in the Chef Infra Client
- [ ] Correctness - A cop that alerts when incorrect coding behavior is being used
- [ ] Sharing - A cop that alerts to missing functionality necessary for sharing cookboooks with others
- [ ] Style - A cop that alerts to a style best practice
- [ ] Simplification - A cop that alerts to ways code can be simplified through refactoring
- [ ] Effortless - A cop that alerts on code that must be resolved to move to the Effortless pattern
- [ ] Policyfiles - A cop that alerts on code that must be resolved to move to the Policyfiles pattern

### Describe the new cop:
These should be done as standard mash attributes instead

### What it would trigger on:

```ruby
node.platform
node.platform_family
node.platform_version
node.fqdn
node.hostname
```

### What it would autocorrect to if applicable

```ruby
node['platform']
node['platform_family']
node['platform_version']
```

**Comment by lamont-granquist** [comment]
should probably trigger on most of these:

```
% ohai | ruby -rjson -e 'puts JSON.parse(STDIN.read).keys.sort'
chef_packages
cloud
command
counters
cpu
current_user
dmi
docker
domain
etc
filesystem
fqdn
hardware
hostname
ip6address
ipaddress
kernel
keys
languages
macaddress
machinename
memory
network
ohai_time
os
os_version
platform
platform_build
platform_family
platform_version
root_group
shard_seed
shells
time
uptime
uptime_seconds
virtualbox
virtualization
```

and when the top level matches then it should convert the next methods as well...

**Comment by lamont-granquist** [comment]
ones without subkeys, although i think node['cloud'] is a bug:

```
% ohai | ruby -rjson -e 'puts JSON.parse(STDIN.read).select { |k,v| !v.is_a?(Hash) && !v.is_a?(Array) }.keys.sort'
cloud
current_user
domain
fqdn
hostname
ip6address
ipaddress
macaddress
machinename
ohai_time
os
os_version
platform
platform_build
platform_family
platform_version
root_group
shard_seed
uptime
uptime_seconds
```

**Comment by tas50** [comment]
yeah that's probably a good list without the subkeys. I didn't want to autocorrect the subkeys since that would horribly mess up cookbook code.

**Comment by lamont-granquist** [comment]
hmmm yeah, `node.foo.bar.baz.each` needs to stop before `each` which complicates everything greatly...
