### ISSUE TITLE
Conflicting Ruby Syntax Checking

### ISSUE THREAD

**Issue by GitBytes** [chef/cookstyle#21]
I found that Rubocop and Cookstyle often don't agree on how to do ruby syntax by default. For example, one that flaps is the `Avoid comma after the last item of a hash` cop.

Given a hash of:
```
{
  foo: 'bar',
  foo2: 'bar2'
}
```
Cookstyle wants to correct this syntax to the following:
```
{
  foo: 'bar',
  foo2: 'bar2',
}
```
Then when I run rubocop again with the default cops, it wants to take the trailing comma back out, and round and round we go.

I really don't care which standard is decided on but it would be great to have them both reflect the same rule here since they are directly conflicting at this point. In my opinion, I'm not convinced everyone should be required to create a `.rubocop.yml` in every cookbook they are working on to address this one or other such conflicting rules going forward but then again, that is my opinion..

What is the greater opinion on "choosing" or "not choosing" between rubocop and cookstyle? Should I use one to rule them all from a syntax perspective? It is pretty clear that Cookstyle is trying to solve a very similar issue as Rubocop but from a Chef angle. If it is not a full replacement, would you advise just using one anyhow? Thanks for you time in advance.

**Comment by coderanger** [comment]
I mean we did choose, `cookstyle` is the choice. Rubocop's defaults are just that, defaults. If you want a different set of default opinions that is a little more tailored to cookbooks, use `cookstyle`. Or make your own :)

**Comment by GitBytes** [comment]
Thanks @coderanger for getting back to me!. Noted, and I will go forth and setup custom rules or choose one over the other. Just wanted to make sure that was where things were headed. Cheers!

**Comment by lamont-granquist** [comment]
yeah this is operating entirely as intentionally designed.

pick one:  rubocop, cookstyle or chefstyle.

do not cross the streams.

for cookbook users cookstyle is the recommendation (and is the requirement for the chef-cookbooks organization)

**Comment by lamont-granquist** [comment]
and to reiterate what @coderanger just said, cookstyle was just a fork of chefstyle which was just a fork of finstyle, which was just a gem wrapper around a custom rubocop.yml along with equality pinning the rubocop engine.

it can be forked again if you've got the motivation.

**Comment by GitBytes** [comment]
@lamont-granquist Nope, I am good with cookstyle. Great so far! Thanks for the follow up, cheers!
