### ISSUE TITLE
 Cookstyle says 'Put a comma after the last item of a multiline hash' 

### ISSUE THREAD

**Issue by naresh89** [chef/cookstyle#22]
It has been observed that for Cookstyle complains to put comma for multi line hash where as rubocop doesn't.

recipes/server.rb:12:24: C: Put a comma after the last item of a multiline hash.
                      ssl_verify_mode: :verify_none
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Is it some conflict with versions?

**Comment by thommay** [comment]
no, cookstyle is a set of choices that we've made for cookbook development. 
You should not run both cookstyle and rubocop, because they make different choices.

**Comment by lamont-granquist** [comment]
dup of #21 as well.

not sure why this isn't totally obvious that this is the whole idea...  README.md needs to be a little more brutally clear about the point?

**Comment by pariminaresh** [comment]
@lamont-granquist @thommay thank you

Choosing cookstyle or rubocop (not both) is clear.In programming the reason behind the choice keeping a comma at the end of a hash which cookstyle suggests, is not clear.

**Comment by thommay** [comment]
The reasons for the trailing comma are twofold:
 - It makes adding lines, and moving lines, safe. You don't have to think about whether you added a trailing comma to the line you moved, or the line above the one you added, you just write the line and finish with a comma, always
 - it makes diffs easier to read, since you just see the line you added, not that line and the line before

**Comment by lamont-granquist** [comment]
There's also "prior art" for what happens with the choice of banning the trailing comma with JSON, and it makes JSON annoying to edit directly.  JSON5 (http://json5.org/) updates the JSON spec to allow trailing commas among other extensions.

**Comment by lamont-granquist** [comment]
There's also other differences like e.g. https://github.com/chef/cookstyle/pull/18
