### ISSUE TITLE
Do not assign to node object without precedence aka node['foo'] << 'bar'

### ISSUE THREAD

**Issue by tas50** [chef/cookstyle#250]
### What category of cop is this?:

Please try to select as few as possible.

- [ ] Deprecation - A cop that alerts to a deprecation in the Chef Infra Client
- [ ] Correctness - A cop that alerts when incorrect coding behavior is being used
- [ ] Sharing - A cop that alerts to missing functionality necessary for sharing cookboooks with others
- [ ] Style - A cop that alerts to a style best practice
- [ ] Simplification - A cop that alerts to ways code can be simplified through refactoring
- [ ] Effortless - A cop that alerts on code that must be resolved to move to the Effortless pattern
- [ ] Policyfiles - A cop that alerts on code that must be resolved to move to the Policyfiles pattern

### Describe the new cop:

None of these should be considered valid:

``` ruby
node['foo'] = 'bar'
node['foo'] << 'bar'
node['foo'] += thing
```

They should all use node.default, node.normal or node.override.

Moved from https://github.com/Foodcritic/foodcritic/issues/237

**Comment by lamont-granquist** [comment]
did this one get done?

the latter two use cases (with the mutators) are particularly important to catch with foodcritic.
