### ISSUE TITLE
Detect invalid cookbook version depedencies

### ISSUE THREAD

**Issue by tas50** [chef/cookstyle#259]
### What category of cop is this?:

Please try to select as few as possible.

- [ ] Deprecation - A cop that alerts to a deprecation in the Chef Infra Client
- [x] Correctness - A cop that alerts when incorrect coding behavior is being used
- [ ] Sharing - A cop that alerts to missing functionality necessary for sharing cookboooks with others
- [ ] Style - A cop that alerts to a style best practice
- [ ] Simplification - A cop that alerts to ways code can be simplified through refactoring
- [ ] Effortless - A cop that alerts on code that must be resolved to move to the Effortless pattern
- [ ] Policyfiles - A cop that alerts on code that must be resolved to move to the Policyfiles pattern

### Describe the new cop:

From the code:

      # Before we began respecting version constraints, we allowed
      # multiple constraints to be placed on cookbooks, as well as the
      # << and >> operators, which are now just < and >.

**Comment by tyler-ball** [comment]
@lamont-granquist Do you know if anyone actually does this and would warrant us needing to write a cop? The idea for a cop came from a comment in the Chef code but we are not sure anyone was actually doing this.
