### ISSUE TITLE
CookbookDependsOnPoise should find all poise-* cookbooks

### ISSUE THREAD

**Issue by lnxchk** [chef/cookstyle#264]
# Version:

current

# Environment:

various

# Scenario:

All poise* cookbooks have been deprecated by the maintainer, so the rule should probably catch all of them.  

# Steps to Reproduce:

A cookbook that depends on any of the following sample of cookbooks will not be flagged:
poise-ruby
poise-python
poise-hoist
There are 21 of these currently listed on the supermarket.

# Expected Result:

All poise* cookbooks should trigger.

# Actual Result:

**Comment by tas50** [comment]
I added hoist which is probably enough for now since the others are technically not deprecated
