### ISSUE TITLE
Add a cop for guard_interpreter :powershell_script in powershell_script resources

### ISSUE THREAD

**Issue by tas50** [chef/cookstyle#269]
### What category of cop is this?:

Please try to select as few as possible.

- [ ] Deprecation - A cop that alerts to a deprecation in the Chef Infra Client
- [ ] Correctness - A cop that alerts when incorrect coding behavior is being used
- [ ] Sharing - A cop that alerts to missing functionality necessary for sharing cookboooks with others
- [ ] Style - A cop that alerts to a style best practice
- [ ] Simplification - A cop that alerts to ways code can be simplified through refactoring
- [ ] Effortless - A cop that alerts on code that must be resolved to move to the Effortless pattern
- [ ] Policyfiles - A cop that alerts on code that must be resolved to move to the Policyfiles pattern

### Describe the new cop:
The default guard in powershell_script is already guard_interpreter :powershell_script as of Chef 13. We should nuke this.

### What it would trigger on:

```ruby
powershell_script 'whatever' do
  guard_interpreter :powershell_script
end
```

### What it would autocorrect to if applicable

```ruby
powershell_script 'whatever' do
end
```

**Comment by afiune** [comment]
Closed by https://github.com/chef/cookstyle/pull/329
