### ISSUE TITLE
ChefStyle/UsePlatformHelpers autocorrect is wrong

### ISSUE THREAD

**Issue by thr3a** [chef/cookstyle#301]
# Version:

5.6.2

# Environment:

Any OS

# Scenario:

recipe code

```ruby
if node["platform_family"] == "debian"

end
```

Execute `bundle exec cookstyle -D --auto-correct` This result is no problem.

```ruby
if platform_family?("debian")

end
```

But, if multiple `node["platform_family"]` are used in one file

```ruby
if node["platform_family"] == "debian"

end


if node["platform_family"] == "rhel"

end
```

Both will be the last value.

```ruby
if platform_family?("rhel")

end

if platform_family?("rhel")

end
```

# Expected Result:

```ruby
if platform_family?("debian")

end

if platform_family?("rhel")

end
```

# Actual Result:

```ruby
if platform_family?("rhel")

end

if platform_family?("rhel")

end
```

**Comment by tas50** [comment]
Well that's not right. I'll see what I can do.

**Comment by tas50** [comment]
Thanks for the report @thr3a. I've fixed this and I'll get a release out hopefully tomorrow

**Comment by thr3a** [comment]
@tas50 Thank you!!
