### ISSUE TITLE
Can the `-r` be moved into `.rubocop.yml` somehow?

### ISSUE THREAD

**Issue by docwhat** [chef/cookstyle#31]
My editors, etc. all are configured to use `rubocop`.  Normally, I change the behavior of `rubocop` by modifying the `.rubocop.yml`.

Is there a way to tell `rubocop` to use `cookstyle` from the `.rubocop.yml` file?

**Comment by lamont-granquist** [comment]
i think "pull requests accepted" is the likely answer.

where i care i set up post commit hooks in repos.  can also be done with .vimrc and setting up different paths, but i've generally switched to preferring hooking git over hooking my editor (running chefstyle on every save was annoying the crap out of me).

**Comment by thommay** [comment]
unfortunately this would be an upstream change and historically they've not been too receptive to things like this.

**Comment by bdwyertech** [comment]
You can load extensions in `rubocop.yml`

The only real gotcha is that you'll need to install the `cookstyle` gem into the gemset you've got rubocop installed in.

https://rubocop.readthedocs.io/en/latest/extensions/
```ruby
require:
  - cookstyle
```

**Comment by lamont-granquist** [comment]
I think that's the best solution were going to have here
