### ISSUE TITLE
cookstyle -a for windows rewrites line endings of original file

### ISSUE THREAD

**Issue by dreamnite** [chef/cookstyle#33]
Using cookstyle -a on a file with unix style (LF) endings adds CRLFs into the file, resulting in "carriage return detected" messages.

Version info:
Cookstyle 1.3.0
  * RuboCop 0.47.1

Chef Development Kit Version: 1.3.43
chef-client version: 12.19.36
delivery version: master (dd319aa632c2f550c92a2172b9d1226478fea997)
berks version: 5.6.4
kitchen version: 1.16.0

**Comment by coderanger** [comment]
This is generally how all Ruby programs work. You can configure Git to translate files for you on Windows.

**Comment by tas50** [comment]
There's a config in Rubocop 0.48 which would let us set the line endings, but we'd have to upgrade the engine and then force everyone over to unix line endings. I'm not sure how people would feel about that.

**Comment by dreamnite** [comment]
This appears to have been a regression in rubocop's autocorrect code. https://github.com/bbatsov/rubocop/issues/1566
https://github.com/bbatsov/rubocop/commit/fcdbd4d5b3850b15cb87b9b52ed14be0238f96d1

**Comment by tas50** [comment]
This should be resolved in the latest release where we enforce LF
