### ISSUE TITLE
5.9.0 not uploaded to rubygems

### ISSUE THREAD

**Issue by zmaupin** [chef/cookstyle#330]
# Version:

5.9.0

# Environment:

Anything

# Scenario:

I want to install cookstyle 5.9.0.

# Steps to Reproduce:

`gem install cookstyle` installs 5.8.1, there are three versions released after this one. 2 days ago 
v5.9.0
v5.8.3
v5.8.2

# Expected Result:

I expect `gem install cookstyle` to install the latest released version

# Actual Result:

`gem install cookstyle` installs 5.8.1

**Comment by tas50** [comment]
Hey @zmaupin 5.9.0 isn't actually released yet. Our Expeditor tooling bumps the version and cuts a gem release on every PR, but those only go to our internal Artifactory server. Once we're ready to make a release and we've completed any additional validation, we promote a specific version to "stable" which pushes it to rubygems. Right now the stable release is 5.8.1. There will most likely be another stable release later this week with 5.9.x

**Comment by zmaupin** [comment]
Ah cool. Thanks for the explanation.
