### ISSUE TITLE
Detect legacy audit mode usage

### ISSUE THREAD

**Issue by tas50** [chef/cookstyle#336]
### What category of cop is this?:

Please try to select as few as possible.

- [ ] Deprecation - A cop that alerts to a deprecation in the Chef Infra Client
- [ ] Correctness - A cop that alerts when incorrect coding behavior is being used
- [ ] Sharing - A cop that alerts to missing functionality necessary for sharing cookboooks with others
- [ ] Style - A cop that alerts to a style best practice
- [ ] Simplification - A cop that alerts to ways code can be simplified through refactoring
- [ ] Effortless - A cop that alerts on code that must be resolved to move to the Effortless pattern
- [ ] Policyfiles - A cop that alerts on code that must be resolved to move to the Policyfiles pattern

### Describe the new cop:
Audit mode was removed in Chef Infra Client 15 and will cause chef-client runs to fail

### What it would trigger on:

```ruby
control_group 'Blog Post Examples' do
  ::RSpec.configure do |c|
    c.filter_run focus: true
  end
 
  control 'SSH' do
    it 'should be listening on port 22' do
      expect(port(22)).to be\_listening
    end
 
    it 'disables root logins over ssh', focus: true do
      expect(file('/etc/ssh/sshd_config').content).to contain('PermitRootLogin no')
    end
  end
end
```

**Comment by lamont-granquist** [comment]
I think control_group is the only valid top-level audit mode DSL method so you only have to match that and warn?

**Comment by tyler-ball** [comment]
Closed by https://github.com/chef/cookstyle/pull/344
