### ISSUE TITLE
Detect legacy yum_repository properties

### ISSUE THREAD

**Issue by tas50** [chef/cookstyle#342]
### What category of cop is this?:

Please try to select as few as possible.

- [ ] Deprecation - A cop that alerts to a deprecation in the Chef Infra Client
- [ ] Correctness - A cop that alerts when incorrect coding behavior is being used
- [ ] Sharing - A cop that alerts to missing functionality necessary for sharing cookboooks with others
- [ ] Style - A cop that alerts to a style best practice
- [ ] Simplification - A cop that alerts to ways code can be simplified through refactoring
- [ ] Effortless - A cop that alerts on code that must be resolved to move to the Effortless pattern
- [ ] Policyfiles - A cop that alerts on code that must be resolved to move to the Policyfiles pattern

### Describe the new cop:
In the yum cookbook 3.0 we changed 3 of the properties to match those in the apt_repository resource. When we shipped the resource in Chef 12.14 those same changes came in. We silently allow folks to use the old names for now, but we should update things so the resources in cookbooks match the docs and so we can remove the backwards compat code in the future.

### What it would trigger on:

```ruby
        #   yum_repository 'OurCo' do
        #     description 'OurCo yum repository'
        #     url 'http://artifacts.ourco.org/foo/bar'
        #     keyurl 'http://artifacts.ourco.org/pub/yum/RPM-GPG-KEY-OURCO-6'
        #     mirrorexpire 1440
        #     action :create
        #   end
```

### What it would autocorrect to if applicable

```ruby
        #   yum_repository 'OurCo' do
        #     description 'OurCo yum repository'
        #     baseurl 'http://artifacts.ourco.org/foo/bar'
        #     gpgkey 'http://artifacts.ourco.org/pub/yum/RPM-GPG-KEY-OURCO-6'
        #     mirror_expire 1440
        #     action :create
        #   end
```

**Comment by tyler-ball** [comment]
Closed by https://github.com/chef/cookstyle/pull/343
