### ISSUE TITLE
Add a chef vault cop for migrations to Effortless

### ISSUE THREAD

**Issue by TheLunaticScripter** [chef/cookstyle#346]
### What category of cop is this?:

Please try to select as few as possible.

- [ ] Deprecation - A cop that alerts to a deprecation in the Chef Infra Client
- [ ] Correctness - A cop that alerts when incorrect coding behavior is being used
- [ ] Sharing - A cop that alerts to missing functionality necessary for sharing cookboooks with others
- [ ] Style - A cop that alerts to a style best practice
- [ ] Simplification - A cop that alerts to ways code can be simplified through refactoring
- [x] Effortless - A cop that alerts on code that must be resolved to move to the Effortless pattern
- [ ] Policyfiles - A cop that alerts on code that must be resolved to move to the Policyfiles pattern

### Describe the new cop:
Chef vault uses the client key issued by the Chef Server to encrypt the data_bag item. As there is no Chef Server in the Effortless pattern a recipe that has a dependency on either the `chef_vault` cookbook or uses the `Chef::Vault::Item` in it will fail at runtime.

### What it would trigger on:

In a recipe
```ruby
ChefVault::Item.load
```
```ruby
chef_vault_item("secrets", "dbpassword")
```
```ruby
chef_vault_item_for_environment('secrets', 'passwords')
```
```ruby
include_recipe 'chef-vault'
```

In a `metadata.rb`
```ruby
depends 'chef-vault
```

### What it would autocorrect to if applicable

I'm not sure this can be autocorrected as this is more a secrets management problem that needs to have a broader discussion.

### Can We Help You Implement This?:
Sure if time permits.

**Comment by scottvidmar** [comment]
I'm almost done with this. I'll PR as soon as I have it completed and tested.

**Comment by scottvidmar** [comment]
The above PR should resolve this issue. :) @TheLunaticScripter @tas50
