### ISSUE TITLE
Detect usage of poise-hoist cookbook

### ISSUE THREAD

**Issue by tas50** [chef/cookstyle#351]
### What category of cop is this?:

Please try to select as few as possible.

- [ ] Deprecation - A cop that alerts to a deprecation in the Chef Infra Client
- [ ] Correctness - A cop that alerts when incorrect coding behavior is being used
- [ ] Sharing - A cop that alerts to missing functionality necessary for sharing cookboooks with others
- [ ] Style - A cop that alerts to a style best practice
- [ ] Simplification - A cop that alerts to ways code can be simplified through refactoring
- [ ] Effortless - A cop that alerts on code that must be resolved to move to the Effortless pattern
- [ ] Policyfiles - A cop that alerts on code that must be resolved to move to the Policyfiles pattern

### Describe the new cop:
poise-hoist is no longer maintained and the functionality is mostly built into Chef Infra Client itself now.

### What it would trigger on:

```ruby
depends 'poise-hoist'
```

**Comment by tyler-ball** [comment]
The complexity here comes not from writing the rules, but figuring out what we suggest to users as the correct replacement.

**Comment by Swathisivakumar** [comment]
Can we at least trigger a warning on dependency of poise-hoist since most people use only the hoisting feature and the suggested fix would to just remove the dependency but because of the risk we shouldn't do an autocorrect.

User who depend on other feature of poise-hoist can ignore the warning.

**Comment by tas50** [comment]
Closed by https://github.com/chef/cookstyle/pull/928
