### ISSUE TITLE
Autocorrect true,false property types

### ISSUE THREAD

**Issue by Xorima** [chef/cookstyle#360]
### What category of cop is this?:

Please try to select as few as possible.

- [ ] Deprecation - A cop that alerts to a deprecation in the Chef Infra Client
- [X] Correctness - A cop that alerts when incorrect coding behavior is being used
- [ ] Sharing - A cop that alerts to missing functionality necessary for sharing cookboooks with others
- [X] Style - A cop that alerts to a style best practice
- [ ] Simplification - A cop that alerts to ways code can be simplified through refactoring
- [ ] Effortless - A cop that alerts on code that must be resolved to move to the Effortless pattern
- [ ] Policyfiles - A cop that alerts on code that must be resolved to move to the Policyfiles pattern

### Describe the new cop:
auto correct properties with type of [true, false] to [TrueClass, FalseClass]

### What it would trigger on:
```ruby
property  :file_log_rotate,     [true, false],  default: true
```

### What it would autocorrect to if applicable

```ruby
property  :file_log_rotate,     [TrueClass, FalseClass],  default: true
```

### Can We Help You Implement This?:
Happy to help if you point me in the right place

**Comment by tas50** [comment]
We went with true/false in #462
