### ISSUE TITLE
Put a comma after the last item of a multiline hash.

### ISSUE THREAD

**Issue by s1mark** [chef/cookstyle#40]
Why does `cookstyle` suggest to put comma after the last hash element?
`rubocop` suggest to remove comma after last element.

*Desired style by cookstyle:*
```ruby
default['cookbook_name']['some_hash'] = {
  'attr01' => 'value01',
  'attr02' => 'value02',
  'attr03' => 'value03',
}
```
*Desired style by rubocop:*
```ruby
default['cookbook_name']['some_hash'] = {
  'attr01' => 'value01',
  'attr02' => 'value02',
  'attr03' => 'value03'
}
```
*version*
* Cookstyle 2.1.0
* RuboCop 0.49.1

**Comment by s1mark** [comment]
Is this the definition that is bind to this check?
https://github.com/chef/cookstyle/blob/master/config/enabled.yml#L947-L950

It seems only array is defined:
```ruby
StyleGuide: '#no-trailing-array-commas'
```

**Comment by thommay** [comment]
Hi,
Rubocop is flat out wrong on this one - trailing commas on each line make the style consistent, make it easier to add new lines and to copy and paste lines.

https://github.com/chef/cookstyle/pull/5 is the discussion. 

I'll be closing this now.
-Thom
