### ISSUE TITLE
Disable Lint/ParenthesesAsGroupedExpression

### ISSUE THREAD

**Issue by thommay** [chef/cookstyle#43]
```
test.rb:4:17: W: Lint/ParenthesesAsGroupedExpression: (...) interpreted as grouped expression.
  etcd_key_value ({
```
it's trying to get the space between the property and the parenthesis removed, but the message is terrible and that's probably bad form for a cookbook anyway

**Comment by coderanger** [comment]
I've seen people tripped up by this a few times, assuming that `foo(x)` == `foo (x)`. But the message is still bad :(

**Comment by lamont-granquist** [comment]
this seems like it catches an important edge case where ruby changes behavior a lot.  message might be confusing, but it seems like it should trip on this.

**Comment by lamont-granquist** [comment]
closing this per comments in #50
