### ISSUE TITLE
Deprecated shell_out helper methods

### ISSUE THREAD

**Issue by lamont-granquist** [chef/cookstyle#599]
Chef 15 removed old methods:

- `shell_out_compact` / `shell_out_compact!` -> `shell_out` / `shell_out!`
- `shell_out_compact_timeout` / `shell_out_compact_timeout!` -> `shell_out` / `shell_out!`
- `shell_out_with_timeout` / `shell_out_with_timeout!` -> `shell_out` / `shell_out!`
- `shell_out_with_systems_locale` / `shell_out_with_systems_locale!` => `shell_out(..., default_env: false)` / `shell_out!(..., default_env: false)`

**Comment by tas50** [comment]
Fixed in 6.3
