### ISSUE TITLE
fail-level not honored 

### ISSUE THREAD

**Issue by Raboo** [chef/cookstyle#64]
Version: 4.0.0
Environment: MacOS, installed via Ruby gems.

# Scenario:
Cookstyle as support for `--fail-level` RuboCop argument.. But that argument is useless without `--display-only-fail-level-offenses`, and cookstyle lacks support for it.

# Steps to Reproduce:
```
$ cookstyle --fail-level W --display-only-fail-level-offenses cookbooks/myawesomecookbook/
```

# Expected Result:
I expect that cookstyle would honor the level i set and only display offenses that are set by argument `--fail-level`

# Actual Result:
```
invalid option: --display-only-fail-level-offenses
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/rubocop-0.55.0/lib/rubocop/options.rb:21:in `parse'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/rubocop-0.55.0/lib/rubocop/cli.rb:37:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/rubocop-0.55.0/bin/rubocop:13:in `block in <top (required)>'
/opt/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/rubocop-0.55.0/bin/rubocop:12:in `<top (required)>'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/cookstyle-3.0.2/bin/cookstyle:13:in `load'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/cookstyle-3.0.2/bin/cookstyle:13:in `<top (required)>'
/usr/local/bin/cookstyle:306:in `load'
/usr/local/bin/cookstyle:306:in `<main>'
```

**Comment by tas50** [comment]
I suspect this a Rubocop bug and we've upgraded rubocop twice since then. Feel free to open this back up if you're still having this issue with cookstyle 5
