### ISSUE TITLE
cookstyle should provide an option to only do Chef* departments

### ISSUE THREAD

**Issue by jaymzh** [chef/cookstyle#734]
This so not quite "major change proposal" but not quite a "bug" in the traditional sense either. But closer to a bug than a design change, so I went with that template.

# Version:

6.3.4

# Environment:

Ubuntu 18.04

# Scenario:

I would like to get all the benefit of cookstyle without also running all the rubocop rules as I already have my own rubocop setup.

Further I would like to keep those two separate as cookstyle often disables rules which I'd then have to track and re-enable.

# Steps to Reproduce:

Run cookstyle, see non-cookstyle rules.

# Current workaround

Currently I have a separate config for cookstyle which disables all rules by default then statically enumerates the Chef departments to enable them. This is OK, but problematic because Chef could add new ones that I miss.

```
$ cat .cookstyle.yml 
inherit_from: .rubocop_common.yml

AllCops:
  TargetChefVersion: 15.9.17
  # don't enable all the rubocop rules. We'll enable
  # just the chef stuff below
  DisabledByDefault: true

# Enable all Chef departments
ChefCorrectness:
  Enabled: true

ChefDeprecations:
  Enabled: true

ChefEffortless:
  Enabled: true

ChefModernize:
  Enabled: true

ChefRedundantCode:
  Enabled: true

ChefSharing:
  Enabled: true

ChefStyle:
  Enabled: true
```

**Comment by tas50** [comment]
Fixed in 7.0

**Comment by jaymzh** [comment]
I scanned through the attached PR, but I don't see an obvious option to enable just cookstyle cops... am I missing it?

**Comment by jaymzh** [comment]
In fact, not fixed.

**Comment by tas50** [comment]
This is a known bug upstream. Short of the upstream project fixing it there's not much we can do. If you want to dig in upstream that would be the place to fix it, but I'm going to close it out here.
