### ISSUE TITLE
Convert File.dirname(__FILE__) to __dir__

### ISSUE THREAD

**Issue by tas50** [chef/cookstyle#736]
### What category of cop is this?:

Please try to select as few as possible.

- [ ] ChefDeprecations - A cop that alerts on a deprecation in the Chef Infra Client
- [ ] ChefCorrectness - A cop that alerts when incorrect coding behavior is being used
- [ ] ChefSharing - A cop that alerts to missing functionality necessary for sharing cookbooks with others
- [ ] ChefStyle - A cop that alerts to a style best practice
- [ ] ChefModernize - A cop that alerts when a cookbook can be simplified or modernized with new functionality
- [ ] ChefEffortless - A cop that alerts on code that must be resolved to move to the Effortless pattern

### Describe the new cop:
File.dirname(__FILE__) is overly complex when you can just use __dir__

### What it would trigger on:

```ruby
File.dirname(__FILE__)
```

### What it would autocorrect to if applicable

```ruby
__dir__
```

**Comment by lamont-granquist** [comment]
that should just go into rubocop shouldn't it?

**Comment by tas50** [comment]
Yep

**Comment by tas50** [comment]
Rubocop itself actually handles the appropriate occurrences and we have that cop enabled now.
