### ISSUE TITLE
Monkey patching of Rubocop::CommentConfig may not work

### ISSUE THREAD

**Issue by AndreiEres** [chef/cookstyle#839]
About that: https://github.com/chef/cookstyle/blob/master/lib/rubocop/monkey_patches/comment_config.rb

In rubocop we moved responsibility for directive comment pattern to Rubocop::DirectiveComment
https://github.com/rubocop/rubocop/commit/976d7419a0a091dca7afdebf9236228aaf0e7f3a

**Comment by tas50** [comment]
This has been updated to the new class. Thanks for the heads up @AndreiEres
