### ISSUE TITLE
Add new cop for resources not running in unified_mode

### ISSUE THREAD

**Issue by ramereth** [chef/cookstyle#844]
### What category of cop is this?:

Please try to select as few as possible.

- [x] Chef/Deprecations - A cop that alerts on a deprecation in the Chef Infra Client
- [ ] Chef/Correctness - A cop that alerts when incorrect coding behavior is being used
- [ ] Chef/Sharing - A cop that alerts to missing functionality necessary for sharing cookbooks with others
- [ ] Chef/Style - A cop that alerts to a style best practice
- [ ] Chef/Modernize - A cop that alerts when a cookbook can be simplified or modernized with new functionality
- [ ] Chef/Effortless - A cop that alerts on code that must be resolved to move to the Effortless pattern
- [ ] Chef/RedundantCode - A cop that detects redundant code regardless of Chef Infra release

### Describe the new cop:

https://github.com/chef/chef/pull/11453

### What it would trigger on:

```ruby
provides :foo_bar
actions :add
```

### What it would autocorrect to if applicable

```ruby
unified_mode true
provides :foo_bar
actions :add
```

**Comment by tas50** [comment]
This is done
