### ISSUE TITLE
Incorrect detection of Style/RedundantBegin

### ISSUE THREAD

**Issue by bmhughes** [chef/cookstyle#847]
# Version:

7.11.1

# Environment:

https://github.com/Xorima/github-cookstyle-runner

# Scenario:

https://github.com/sous-chefs/dhcp/pull/170

A `Style/RedundantBegin` has been detected which results in invalid Ruby when fixed. Unless i'm very much mistaken, with this code being inside a `ruby_block` resources block then the `begin` is required to be syntactically correct.

# Steps to Reproduce:

Run cookstyle

# Expected Result:

Clean run

**Comment by tas50** [comment]
I've disabled this cop in 7.11.3 until rubocop can dig into the failures
