### ISSUE TITLE
Support for `depends` with missing comma in metadata instead of `Lint/ImplicitStringConcatenation`

### ISSUE THREAD

**Issue by collinmcneese** [chef/cookstyle#878]
### What category of cop is this?:

Please try to select as few as possible.

- [ ] Chef/Deprecations - A cop that alerts on a deprecation in the Chef Infra Client
- [X] Chef/Correctness - A cop that alerts when incorrect coding behavior is being used
- [ ] Chef/Sharing - A cop that alerts to missing functionality necessary for sharing cookbooks with others
- [ ] Chef/Style - A cop that alerts to a style best practice
- [ ] Chef/Modernize - A cop that alerts when a cookbook can be simplified or modernized with new functionality
- [ ] Chef/Effortless - A cop that alerts on code that must be resolved to move to the Effortless pattern
- [ ] Chef/RedundantCode - A cop that detects redundant code regardless of Chef Infra release
- [ ] InSpec/Deprecations - A cop that alerts on a deprecation in the Chef InSpec 

### Describe the new cop:

When running `cookstyle` against a local cookbook repository that has incorrectly-formatted `depends` lines which are missing a comma, Cookstyle will report the failure as `Lint/ImplicitStringConcatenation`.  Suggestion for new feature is that we detect `Lint/ImplicitStringConcatenation` for `depends` lines in metadata.rb and suggest how it is supposed to be represented and auto-correct.

### What it would trigger on:

```ruby
name 'some_cookbook_210805'
maintainer 'My Name'
maintainer_email 'my@email.address'
license 'Apache-2.0'
description 'Installs/Configures some_cookbook_210805'
version '0.1.0'
chef_version '>= 15.0'

depends 'some_awesome_cookbook' '= 4.5.5'
depends 'some_other_cool_cookbook' '< 8.0'
```

```plain
# Cookstyle report
$ cookstyle
Inspecting 4 files
.W..

Offenses:

metadata.rb:9:9: W: Lint/ImplicitStringConcatenation: Combine 'some_awesome_cookbook' and '=4.5.5' into a single string literal, rather than using implicit string concatenation. Or, if they were intended to be separate method arguments, separate them with a comma.
depends 'some_awesome_cookbook' '= 4.5.5'
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metadata.rb:10:9: W: Lint/ImplicitStringConcatenation: Combine 'some_other_cool_cookbook' and '< 8.0' into a single string literal, rather than using implicit string concatenation. Or, if they were intended to be separate method arguments, separate them with a comma.
depends 'some_other_cool_cookbook' '< 8.0'
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

4 files inspected, 2 offenses detected
```

### What it would autocorrect to if applicable

```ruby
depends 'some_awesome_cookbook', '= 4.5.5'
depends 'some_other_cool_cookbook', '< 8.0'
```

### Can We Help You Implement This?:

I'm not sure what the best Cop section/name would be for something like this so I didn't suggest one 😁

**Comment by tas50** [comment]
Added in 7.16
