### ISSUE TITLE
Detect old Chef::Platform methods usage

### ISSUE THREAD

**Issue by tas50** [chef/cookstyle#88]
### What category of cop is this?:

Please try to select as few as possible.

- [x] Deprecation - A cop that alerts to a deprecation in the Chef Infra Client
- [ ] Correctness - A cop that alerts when incorrect coding behavior is being used
- [ ] Sharing - A cop that alerts to missing functionality necessary for sharing cookboooks with others
- [ ] Style - A cop that alerts to a style best practice
- [ ] Simplification - A cop that alerts to ways code can be simplified through refactoring
- [ ] Effortless - A cop that alerts on code that must be resolved to move to the Effortless pattern
- [ ] Policyfiles - A cop that alerts on code that must be resolved to move to the Policyfiles pattern

### Describe the new cop:
We removed many old Chef::Platform methods in Chef 13

### What it would trigger on:
```ruby
resource = Chef::Resource::File.new("/tmp/foo.xyz", run_context)
provider = Chef::Platform.provider_for_resource(resource, :create)

resource = Chef::Resource::File.new("/tmp/foo.xyz", run_context)
provider = Chef::Platform.find_provider("ubuntu", "16.04", resource)

resource = Chef::Resource::File.new("/tmp/foo.xyz", run_context)
provider = Chef::Platform.find_provider_for_node(node, resource)
```

### What it would autocorrect to if applicable
```ruby
resource = Chef::Resource::File.new("/tmp/foo.xyz", run_context)
provider = resource.provider_for_action(:create)
```

**Comment by lamont-granquist** [comment]
something like `Chef::ProviderResolver.new(node, self, action).resolve` would be the replacement for `Chef::Platform.find_provider_for_node(node, resource)` but be careful of klass-vs-instance issues in the return type. offhand i have no idea what the latter used to return.

for Chef::Platform.find_provider("ubuntu", "16.04", resource) you'd have to synthetically create a node and feed it into `Chef::ProviderResolver.new(node, self, action).resolve`.  if that isn't an actual problem that needs solving i wouldn't bother solving it.  hopefully not many cookbooks use that or they're so old and broken nobody cares...

**Comment by tas50** [comment]
Fixed by https://github.com/chef/cookstyle/pull/450
